# Generated by Django 6.0.4 on 2026-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_accessed",
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
    ]
